# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-09 07:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ServerType', models.CharField(max_length=20, verbose_name='\u8bbe\u5907\u7c7b\u578b')),
            ],
        ),
        migrations.CreateModel(
            name='ServerList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Supplier', models.CharField(max_length=8, verbose_name='\u4f9b\u5e94\u5546')),
                ('Model', models.CharField(max_length=20, verbose_name='\u670d\u52a1\u5668\u578b\u53f7')),
                ('SN', models.CharField(max_length=20)),
                ('PN', models.CharField(blank=True, max_length=20)),
                ('Location', models.CharField(blank=True, max_length=10, verbose_name='\u673a\u67dc\u4f4d\u7f6e')),
                ('Management_ip', models.GenericIPAddressField(default='192.168.0.120', verbose_name='\u7ba1\u7406\u53e3IP')),
                ('Hostname', models.CharField(max_length=20, verbose_name='\u8ba1\u7b97\u673a\u540d')),
                ('IpAddr1', models.GenericIPAddressField()),
                ('IpAddr2', models.GenericIPAddressField(blank=True, null=True)),
                ('CpuType', models.CharField(max_length=40, verbose_name='CPU \u578b\u53f7')),
                ('CpuPhysicsCore', models.IntegerField(default=1, verbose_name='CPU \u7269\u7406\u6838\u6570')),
                ('CpuLogicCore', models.IntegerField(default=2, verbose_name='CPU \u903b\u8f91\u6838\u6570')),
                ('Memory', models.IntegerField(default=2, verbose_name='\u5185\u5b58\u5927\u5c0f')),
                ('HDD', models.IntegerField(default=50, verbose_name='\u78c1\u76d8\u5927\u5c0f')),
                ('RAID', models.IntegerField(blank=True, null=True, verbose_name='RAID\u7c7b\u578b')),
                ('Os', models.CharField(blank=True, max_length=16, verbose_name='\u64cd\u4f5c\u7cfb\u7edf\u7c7b\u578b')),
                ('OsVersion', models.CharField(blank=True, max_length=40, verbose_name='\u7cfb\u7edf\u7248\u672c')),
                ('AddDate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='addtime')),
                ('ModDate', models.DateTimeField(auto_now=True, verbose_name='chagetime')),
                ('ServerType_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ttsx_app.DeviceList')),
            ],
        ),
    ]
