# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-09 09:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ttsx_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverlist',
            name='AddDate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u521b\u5efa\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='serverlist',
            name='ModDate',
            field=models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4'),
        ),
    ]
