# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-09 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttsx_app', '0003_auto_20180209_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverlist',
            name='CpuLogicCore',
            field=models.IntegerField(default='0', verbose_name='CPU \u903b\u8f91\u6838\u6570'),
        ),
        migrations.AlterField(
            model_name='serverlist',
            name='CpuPhysicsCore',
            field=models.IntegerField(default='0', verbose_name='CPU \u7269\u7406\u6838\u6570'),
        ),
        migrations.AlterField(
            model_name='serverlist',
            name='CpuType',
            field=models.CharField(default='0', max_length=40, verbose_name='CPU \u578b\u53f7'),
        ),
        migrations.AlterField(
            model_name='serverlist',
            name='HDD',
            field=models.IntegerField(default='0', verbose_name='\u78c1\u76d8\u5927\u5c0f'),
        ),
        migrations.AlterField(
            model_name='serverlist',
            name='Memory',
            field=models.IntegerField(default='0', verbose_name='\u5185\u5b58\u5927\u5c0f'),
        ),
    ]
