# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-09 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttsx_app', '0004_auto_20180209_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverlist',
            name='CpuType',
            field=models.CharField(max_length=40, verbose_name='CPU \u578b\u53f7'),
        ),
    ]
