# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-09 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttsx_app', '0005_auto_20180209_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverlist',
            name='CpuLogicCore',
            field=models.IntegerField(default='1', verbose_name='CPU \u903b\u8f91\u6838\u6570'),
        ),
        migrations.AlterField(
            model_name='serverlist',
            name='CpuPhysicsCore',
            field=models.IntegerField(default='1', verbose_name='CPU \u7269\u7406\u6838\u6570'),
        ),
        migrations.AlterField(
            model_name='serverlist',
            name='HDD',
            field=models.IntegerField(default='50', verbose_name='\u78c1\u76d8\u5927\u5c0f'),
        ),
        migrations.AlterField(
            model_name='serverlist',
            name='Memory',
            field=models.IntegerField(default='2', verbose_name='\u5185\u5b58\u5927\u5c0f'),
        ),
    ]
